<div id="sidebar">
	<a href="#" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>
	<ul id="normalmenu">
		<li class="active"><a href="<%=base %>jsp/index.jsp"><i class="icon icon-home"></i> <span class="slb-menu-word">Dashboard</span></a></li>
		<li class="submenu">
			<a href="#"><i class="icon icon-th-list"></i> <span class="slb-menu-word">Form elements</span> <span class="label">3</span></a>
			<ul>
				<li><a href="<%=base %>jsp/form-common.jsp"><span class="slb-menu-word slb-submenu" slb-word="Common elements">Common elements</span></a></li>
				<li><a href="<%=base %>jsp/form-validation.jsp"><span class="slb-menu-word slb-submenu" slb-word="Validation">Validation</span></a></li>
				<li><a href="<%=base %>jsp/form-wizard.jsp"><span class="slb-menu-word slb-submenu" slb-word="Wizard">Wizard</span></a></li>
			</ul>
		</li>
		<li><a href="<%=base %>jsp/buttons.jsp"><i class="icon icon-tint"></i> <span class="slb-menu-word">Buttons &amp; icons</span></a></li>
		<li><a href="<%=base %>jsp/interface.jsp"><i class="icon icon-pencil"></i> <span class="slb-menu-word">Interface elements</span></a></li>
		<li><a href="<%=base %>jsp/tables.jsp"><i class="icon icon-th"></i> <span class="slb-menu-word">Tables</span></a></li>
		<li><a href="<%=base %>jsp/grid.jsp"><i class="icon icon-th-list"></i> <span class="slb-menu-word">Grid Layout</span></a></li>
		<li class="submenu">
			<a href="#"><i class="icon icon-file"></i> <span class="slb-menu-word">Sample pages</span> <span class="label">5</span></a>
			<ul>
				<li><a href="<%=base %>jsp/jdbcTemplate.jsp"><span class="slb-menu-word slb-submenu" slb-word="JdbcTemplate">JdbcTemplate</span></a></li>
				<li><a href="<%=base %>jsp/invoice.jsp"><span class="slb-menu-word slb-submenu" slb-word="Invoice">Invoice</span></a></li>
				<li><a href="<%=base %>jsp/chat.jsp"><span class="slb-menu-word slb-submenu" slb-word="Support chat">Support chat</span></a></li>
				<li><a href="<%=base %>jsp/calendar.jsp"><span class="slb-menu-word slb-submenu" slb-word="Calendar">Calendar</span></a></li>
				<li><a href="<%=base %>jsp/gallery.jsp"><span class="slb-menu-word slb-submenu" slb-word="Gallery">Gallery</span></a></li>
			</ul>
		</li>
		<li>
			<a href="<%=base %>jsp/charts.jsp"><i class="icon icon-signal"></i> <span class="slb-menu-word">Charts &amp; graphs</span></a>
		</li>
		<li>
			<a href="<%=base %>jsp/widgets.jsp"><i class="icon icon-inbox"></i> <span class="slb-menu-word">Widgets</span></a>
		</li>
		<li>
			<a id="menuarrow" href="#"><i class="icon-white icon-arrow-left"></i> <span class="slb-menu-word">Fold &amp; Expansion</span></a>
		</li>
	</ul>
</div>